"""feed seen state

Revision ID: 1aab6327fbf6
Revises: 65b0991fdbd1
Create Date: 2026-08-25 23:04:20.571365
"""
from alembic import op
import sqlalchemy as sa


revision = '1aab6327fbf6'
down_revision = '65b0991fdbd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_state',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'feed_id')
    )
    op.create_index(op.f('ix_feed_state_updated_at'), 'feed_state', ['updated_at'], unique=False)

    # Seed every existing subscription as seen now. Without this the badge would light up
    # with each show's entire back catalogue the moment this ships -- exactly the noise the
    # change is meant to remove.
    op.execute(
        "INSERT INTO feed_state (user_id, feed_id, last_seen_at, updated_at) "
        "SELECT u.id, f.id, now(), now() FROM users u CROSS JOIN feeds f"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feed_state_updated_at'), table_name='feed_state')
    op.drop_table('feed_state')
    # ### end Alembic commands ###
