"""totp second factor

Revision ID: 30f124d057e3
Revises: be2e9d0800f3
Create Date: 2026-08-26 16:05:47.939983
"""
from alembic import op
import sqlalchemy as sa


revision = '30f124d057e3'
down_revision = 'be2e9d0800f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('totp_last_step', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_last_step')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
