"""feed deletion tombstones

Revision ID: 4ae1901f57b5
Revises: 1aab6327fbf6
Create Date: 2026-08-26 15:00:07.454462
"""
from alembic import op
import sqlalchemy as sa


revision = '4ae1901f57b5'
down_revision = '1aab6327fbf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_feeds',
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('feed_url', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('feed_id')
    )
    op.create_index(op.f('ix_deleted_feeds_deleted_at'), 'deleted_feeds', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deleted_feeds_deleted_at'), table_name='deleted_feeds')
    op.drop_table('deleted_feeds')
    # ### end Alembic commands ###
