"""global auto download count

Revision ID: 65b0991fdbd1
Revises: fbd67f5abb3e
Create Date: 2026-08-25 22:54:56.459931
"""
from alembic import op
import sqlalchemy as sa


revision = '65b0991fdbd1'
down_revision = 'fbd67f5abb3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'settings',
        sa.Column('global_auto_download_count', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('settings', 'global_auto_download_count', server_default=None)

    # NULL now means "inherit the global".
    op.alter_column('feeds', 'auto_download_count', existing_type=sa.INTEGER(), nullable=True)

    # Feeds sitting at 0 were never a deliberate choice -- 0 was simply the old column
    # default, and before this migration there was no way to express "inherit". Converting
    # them preserves behaviour exactly, because the global starts at 0 too, while letting a
    # global set later actually reach them. A non-zero value is a real decision and stays.
    op.execute("UPDATE feeds SET auto_download_count = NULL WHERE auto_download_count = 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("UPDATE feeds SET auto_download_count = 0 WHERE auto_download_count IS NULL")
    op.alter_column('feeds', 'auto_download_count', existing_type=sa.INTEGER(), nullable=False)
    op.drop_column('settings', 'global_auto_download_count')
