"""add feeds.resolved_url

Revision ID: b29ab33d812f
Revises: db0f658f29e0
Create Date: 2026-08-25 22:26:41.535227
"""
from alembic import op
import sqlalchemy as sa


revision = 'b29ab33d812f'
down_revision = 'db0f658f29e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('resolved_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'resolved_url')
    # ### end Alembic commands ###
