"""restore the transcript search index

Revision ID: d4e8b2c7a915
Revises: c7a1e4d9b3f2
Create Date: 2026-09-24 10:00:00.000000

Created by 666969944538 and dropped again by afa3fb403917, an autogenerated migration
that did not find the index in the model and took it for a stray.
"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd4e8b2c7a915'
down_revision: Union[str, None] = 'c7a1e4d9b3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_episodes_transcript_fts ON episodes "
        "USING gin (to_tsvector('english', coalesce(transcript_text, '')))"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_episodes_transcript_fts")
