"""initial schema

Revision ID: db0f658f29e0
Revises: 
Create Date: 2026-08-25 18:47:50.495487
"""
from alembic import op
import sqlalchemy as sa


revision = 'db0f658f29e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artwork_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetch_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artwork_cache_url_hash'), 'artwork_cache', ['url_hash'], unique=True)
    op.create_table('feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_url', sa.Text(), nullable=False),
    sa.Column('podcast_index_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=False),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetch_error', sa.Text(), nullable=True),
    sa.Column('fetch_error_count', sa.Integer(), nullable=False),
    sa.Column('auto_download_count', sa.Integer(), nullable=False),
    sa.Column('retention_mode', sa.Enum('after_played', 'after_download', 'never', name='retention_mode', native_enum=False), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_url')
    )
    op.create_index(op.f('ix_feeds_podcast_index_id'), 'feeds', ['podcast_index_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_retention_mode', sa.Enum('after_played', 'after_download', 'never', name='retention_mode', native_enum=False), nullable=False),
    sa.Column('global_retention_days', sa.Integer(), nullable=False),
    sa.Column('download_dir_max_bytes', sa.BigInteger(), nullable=True),
    sa.Column('refresh_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('enclosure_url', sa.Text(), nullable=True),
    sa.Column('enclosure_type', sa.String(length=128), nullable=True),
    sa.Column('enclosure_bytes', sa.BigInteger(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('local_bytes', sa.BigInteger(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_id', 'guid', name='uq_episodes_feed_guid')
    )
    op.create_index(op.f('ix_episodes_feed_id'), 'episodes', ['feed_id'], unique=False)
    op.create_index(op.f('ix_episodes_first_seen_at'), 'episodes', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_episodes_published_at'), 'episodes', ['published_at'], unique=False)
    op.create_index(op.f('ix_episodes_updated_at'), 'episodes', ['updated_at'], unique=False)
    op.create_table('download_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('queued', 'running', 'done', 'failed', name='job_state', native_enum=False), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('queue', 'auto', 'manual', name='job_source', native_enum=False), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_jobs_episode_id'), 'download_jobs', ['episode_id'], unique=False)
    op.create_index(op.f('ix_download_jobs_next_attempt_at'), 'download_jobs', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_download_jobs_state'), 'download_jobs', ['state'], unique=False)
    op.create_table('episode_state',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('played', sa.Boolean(), nullable=False),
    sa.Column('position_seconds', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'episode_id')
    )
    op.create_index(op.f('ix_episode_state_updated_at'), 'episode_state', ['updated_at'], unique=False)
    op.create_table('queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'episode_id', name='uq_queue_user_episode')
    )
    op.create_index(op.f('ix_queue_user_id'), 'queue', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_user_id'), table_name='queue')
    op.drop_table('queue')
    op.drop_index(op.f('ix_episode_state_updated_at'), table_name='episode_state')
    op.drop_table('episode_state')
    op.drop_index(op.f('ix_download_jobs_state'), table_name='download_jobs')
    op.drop_index(op.f('ix_download_jobs_next_attempt_at'), table_name='download_jobs')
    op.drop_index(op.f('ix_download_jobs_episode_id'), table_name='download_jobs')
    op.drop_table('download_jobs')
    op.drop_index(op.f('ix_episodes_updated_at'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_published_at'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_first_seen_at'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_feed_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_index(op.f('ix_feeds_podcast_index_id'), table_name='feeds')
    op.drop_table('feeds')
    op.drop_index(op.f('ix_artwork_cache_url_hash'), table_name='artwork_cache')
    op.drop_table('artwork_cache')
    # ### end Alembic commands ###
