"""add default playback rate

Revision ID: fbd67f5abb3e
Revises: b29ab33d812f
Create Date: 2026-08-25 22:48:10.737281
"""
from alembic import op
import sqlalchemy as sa


revision = 'fbd67f5abb3e'
down_revision = 'b29ab33d812f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so the existing settings row satisfies NOT NULL, then dropped: the
    # application supplies the default from here on, and leaving it would mean the value
    # lives in two places.
    op.add_column(
        'settings',
        sa.Column('default_playback_rate', sa.Float(), nullable=False, server_default='1.0'),
    )
    op.alter_column('settings', 'default_playback_rate', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'default_playback_rate')
    # ### end Alembic commands ###
